# Generated by Django 4.2.16 on 2024-10-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Student account'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Teacher account'),
        ),
    ]
