# Generated by Django 4.2.16 on 2024-10-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usermodel_is_student_usermodel_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='is_student',
            field=models.BooleanField(default=False, verbose_name='Whizzer account'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Creator account'),
        ),
    ]
