# Generated by Django 4.2.16 on 2024-10-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermodel_date_joined_alter_usermodel_last_login'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
