# Generated by Django 4.2.16 on 2024-10-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_usermodel_options_usermodel_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
