# Generated by Django 4.2.16 on 2024-10-22 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_choice_text_quizattempt_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
